### ISSUE TITLE
Read design

### ISSUE THREAD

**Issue by finswimmer** [qiaseq/smcounter-v2-paper#1]
Hello,

I'm trying to test my own pipeline with your data used for validation smcounter. What I'm struggling now, is the read design for the different datasets.

So far I found out the dataset M0253 R1 starts with the primer and R2 with a 12bp UMI followed by the universal primer sequence ATTGGAGTCCT. Correct?

But how does it look like in N13532? The UMI seems to be as well in R2. But how long is it? 23bp get constantly soft-clipped, if I'm aligning the data without any trimming. There seems to be no universal sequence like in the first dataset. So is my UMI 23bp long? Or also 12bp? But what are the other 11bp?

Furthermore I've found the bed files for the captured regions here: https://github.com/qiaseq/qiaseq-dna/issues/15

Could you please also provide the primer files for correct trimming?

Thanks a lot!

fin swimmer

**Comment by rpadmanabhan** [comment]
Hi,
That is correct the R1 starts with the primer, and the R2 with a 12 bp UMI followed by the 11 b.p common sequence ATTGGAGTCCT
It is the same for N13532, the reason you do not see the 11-mer on the R2 here is because this sample was sequenced on a NextSeq which has trouble reading low diversity base positions. The UMIs being different sequences are read correctly from instrument.

I put the primer files are here (the coordinates correspond to the 3' design site , 0 -> +ve strand , 1 -> -ve strand) : 
https://storage.googleapis.com/smcounterv2-paper/N13532/CDHS-13532Z-10181.primer3.txt
https://storage.googleapis.com/smcounterv2-paper/M0253/DHS-101Z.primer3.txt
https://storage.googleapis.com/smcounterv2-paper/N0261/CDHS-13907Z-562.primer3.txt

**Comment by finswimmer** [comment]
Thanks for the quick reply and the additional information!
